from gaphor.diagram.general import *
from gaphor.UML3.classesonto import *
from gaphor.UML3.profile import *
from gaphor.UML3.profile.heritage import *
from gaphor.UML3.profile.material import *
from gaphor.UML3.profile.mediation import *
from gaphor.UML3.profile.derivation import *
from gaphor.UML3.profile.dependencyblack import *
from gaphor.UML3.profile.dependencywhite import *
from gaphor.UML3.profile.componentof import *
from gaphor.UML3.profile.characterization import *
from gaphor.UML3.profile.partwhole import *
from gaphor.UML3.profile.partwholeblack import *
from gaphor.UML3.profile.structuration import *
from gaphor.UML3.profile.containment import *
from gaphor.UML3.profile.memberof import *
from gaphor.UML3.profile.memberofblack import *
from gaphor.UML3.profile.subcollectionof import *
from gaphor.UML3.profile.subquantityof import *
from gaphor.UML3.profile.formal import *
