# This file is generated by profile_coder.py. DO NOT EDIT!
from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, Callable, List, Optional

from gaphor.core.modeling.properties import (
    association,
    attribute,
    derived,
    derivedunion,
    enumeration,
    redefine,
    relation_many,
    relation_one,
)
from gaphor.core.modeling import (
    Comment,
    Diagram,
    Element,
    NamedElement,
    PackageableElement,
    StyleSheet,
)
from gaphor.UML import (
    Abstraction,
    AcceptEventAction,
    ActivityEdge,
    ActivityPartition,
    ActivityGroup,
    Activity,
    Action,
    Artifact,
    Association,
    AddStructuralFeatureValueAction,
    Behavior,
    ChangeEvent,
    Class,
    Classifier,
    Comment,
    Component,
    Connector,
    ConnectorEnd,
    Constraint,
    DataType,
    Dependency,
    DirectedRelationship,
    DeploymentTarget,
    Element,
    ElementImport,
    Extend,
    Feature,
    Generalization,
    GeneralOrdering,
    InstanceSpecification,
    InvocationAction,
    Include,
    Interaction,
    InteractionFragment,
    NamedElement,
    Namespace,
    MultiplicityElement,
    ObjectNode,
    Operation,
    Optional,
    Parameter,
    ParameterSet,
    PackageImport,
    PackageMerge,
    Package,
    Port,
    Property,
    Pseudostate,
    RedefinableElement,
    Realization,
    Relationship,
    StructuralFeature,
    State,
    StateInvariant,
    Stereotype,
    Slot,
    Transition,
    Trigger,
    Type,
)

class Classifier(Namespace, Type, RedefinableElement):
    isAbstract: attribute[int]
    ownedUseCase: relation_many[UseCase]
    generalization: relation_many[Generalization]
    Heritage: relation_many[Heritage]
    useCase: relation_many[UseCase]
    redefinedClassifier: relation_many[Classifier]
    attribute: relation_many[Property]
    feature: relation_many[Feature]
    general: derived[Classifier]
    inheritedMember: derivedunion[NamedElement]


class Heritage(Association):
    pass

class Dependencyblack(Association):
    pass

class Dependencywhite(Association):
    pass

class Formal(Association):
    pass

class Material(Association):
    pass

class Mediation(Association):
    pass

class Characterization(Association):
    pass

class Derivation(Association):
    pass

class Structuration(Association):
    pass

class Partwhole(Association):
    pass

class Partwholeblack(Association):
    pass

class Memberof(Association):
    pass

class Memberofblack(Association):
    pass

class Subcollectionof(Association):
    pass

class Subquantityof(Association):
    pass

class Componentof(Association):
    pass

class Containment(Association):
    pass

class AcceptChangeStructuralFeatureEventAction(AcceptEventAction):
    pass


class ElementPropertyPath(Element):
    propertyPath: relation_many[Property]


class AddFlowPropertyValueOnNestedPortAction(
    AddStructuralFeatureValueAction, ElementPropertyPath
):
    pass


class AdjuntProperty(Property):
    principal: relation_one[Element]


class DirectedRelationshipPropertyPath(DirectedRelationship):
    sourcePropertyPath: relation_many[Property]
    targetContext: relation_one[Classifier]
    targetPropertyPath: relation_many[Property]
    sourceContext: relation_one[Classifier]


class Allocate(Abstraction, DirectedRelationshipPropertyPath):
    pass


class AllocateActivityPartition(ActivityPartition):
    pass


class BindingConnector(Connector):
    pass


class EndPathMultiplicity(Property):
    pass


class BoundReference(EndPathMultiplicity):
    boundend: relation_many[ConnectorEnd]


class ChangeSructuralFeatureEvent(ChangeEvent):
    structuralFeature: relation_one[StructuralFeature]


class ClassifierBehaviorProperty(Property):
    pass


class Conform(Generalization):
    pass


class ConnectorProperty(Property):
    connector: relation_one[Connector]


class Rate(ActivityEdge, Parameter):
    rate: relation_many[InstanceSpecification]


class Continuous(Rate):
    pass


class ControlOperator(Behavior):
    pass


class Trace(Dependency, DirectedRelationshipPropertyPath):
    pass


class Copy(Trace):
    pass


class DeriveReqt(Trace):
    pass


class DirectedFeature(Feature):
    featureDirection: enumeration


class Discrete(Rate):
    pass


class DistributedProperty(Property):
    pass


class ElementGroup(Comment):
    name: attribute[str]
    orderedMember: relation_many[Element]


class Expose(Dependency):
    pass


class FlowProperty(Property):
    direction: enumeration


class FullPort(Port):
    pass


class InvocationOnNestedPortAction(ElementPropertyPath, InvocationAction):
    onNestedPort: relation_many[Port]


class NestedConnectorEnd(ConnectorEnd, ElementPropertyPath):
    pass


class NoBuffer(ObjectNode):
    pass


class Overwrite(ObjectNode):
    pass


class ParticipantProperty(Property):
    end_: relation_one[Property]


class Probability(ActivityEdge, ParameterSet):
    probability: attribute[str]


class Problem(Comment):
    pass


class PropertySpecificType(Classifier):
    pass


class ProxyPort(Port):
    pass


class Rationale(Comment):
    pass


class Refine(Dependency, DirectedRelationshipPropertyPath):
    pass


class Satisfy(Trace):
    pass


class Stakeholder(Classifier):
    concernList: relation_many[Comment]


#aqui foram adicionados estereótipos da ontouml
class StereotypeKind(Class):
    pass

class StereotypeSubkind(Class):
    pass

class StereotypePhase(Class):
    pass

class StereotypeRole(Class):
    pass

class StereotypeCollective(Class):
    pass

class StereotypeQuantity(Class):
    pass

class StereotypeRelator(Class):
    pass

class StereotypeCategory(Class):
    pass

class StereotypeRolemixin(Class):
    pass

class StereotypeMixin(Class):
    pass

class StereotypePhasemixin(Class):
    pass

class StereotypeMode(Class):
    pass

class StereotypeQuality(Class):
    pass

class Teste(Association):
    pass

class Tagged(Property):
    nonunique: relation_many[bool]
    ordered: relation_many[bool]
    subsets: attribute[str]


class TestCase(Behavior):
    pass


class TriggerOnNestedPort(ElementPropertyPath, Trigger):
    onNestedPort: relation_many[Port]


class ValueType(DataType):
    quantityKind: relation_one[InstanceSpecification]
    unit: relation_one[InstanceSpecification]


class Verify(Trace):
    pass


class View(Class):
    pass


class Viewpoint(Class):
    concernList: relation_many[Comment]
    language: attribute[str]
    presentation: attribute[str]
    purpose: attribute[str]
    stakeholder: relation_many[Stakeholder]



AdjuntProperty.principal = association("principal", Element, upper=1)
BoundReference.boundend = association("boundend", ConnectorEnd, upper=1)
ChangeSructuralFeatureEvent.structuralFeature = association(
    "structuralFeature", StructuralFeature, upper=1
)
ConnectorProperty.connector = association("connector", Connector, upper=1)
DirectedFeature.featureDirection = enumeration(
    "kind", ("providedRequired", "provided", "required"), "providedRequired"
)
DirectedRelationshipPropertyPath.sourceContext = association(
    "sourceContext", Classifier, upper=1
)
DirectedRelationshipPropertyPath.sourcePropertyPath = association(
    "sourcePropertyPath", Property
)
DirectedRelationshipPropertyPath.targetContext = association(
    "targetContext", Classifier, upper=1
)
DirectedRelationshipPropertyPath.targetPropertyPath = association(
    "targetPropertyPath", Property
)
ElementGroup.name = attribute("name", str)
ElementGroup.orderedMember = association("orderedMember", Element)
ElementPropertyPath.propertyPath = association("propertyPath", Property, lower=1)
FlowProperty.direction = enumeration("kind", ("inout", "in", "out"), "inout")
InvocationOnNestedPortAction.onNestedPort = association("onNestedPort", Port, lower=1)
ParticipantProperty.end_ = association("end_", Property, upper=1)
Probability.probability = attribute("probability", str)
Rate.rate = association("rate", InstanceSpecification, upper=1)
Stakeholder.concernList = association("concernList", Comment)
Tagged.nonunique = association("nonunique", bool, upper=1)
Tagged.ordered = association("ordered", bool, upper=1)
Tagged.subsets = attribute("subsets", str)
TriggerOnNestedPort.onNestedPort = association("onNestedPort", Port, lower=1)
ValueType.quantityKind = association("quantityKind", InstanceSpecification, upper=1)
ValueType.unit = association("unit", InstanceSpecification, upper=1)
Viewpoint.concernList = association("concernList", Comment)
Viewpoint.language = attribute("language", str)
Viewpoint.presentation = attribute("presentation", str)
Viewpoint.purpose = attribute("purpose", str)
Viewpoint.stakeholder = association("stakeholder", Stakeholder)
